steps:
  - name: 'node:20-slim'
    id: deploy-static
    entrypoint: bash
    args:
      - '-c'
      - |
        npm install -g firebase-tools --quiet
        firebase deploy --only hosting --project clive-6d22e

timeout: 120s
